### ISSUE TITLE
Sketch too big

### ISSUE THREAD

**Issue by imaustink** [plumgeek/PlumGeek-Ringo-Robot#1]
I can't install the pre-loaded behaviors because it's too big to for the Ringo's internal memories.

```
Binary sketch size: 33,890 bytes (of a 30,720 byte maximum)
processing.app.debug.RunnerException: Sketch too big; see http://www.arduino.cc/en/Guide/Troubleshooting#size for tips on reducing it.
    at processing.app.Sketch.size(Sketch.java:1653)
    at processing.app.Sketch.build(Sketch.java:1586)
    at processing.app.Sketch.build(Sketch.java:1562)
    at processing.app.Editor$DefaultRunHandler.run(Editor.java:1899)
    at java.lang.Thread.run(Thread.java:695)
```

How can this be? It was made for Ringo! Any ideas?

Thanks!

**Comment by plumgeek** [comment]
Try using Arduino IDE 1.6.5 or later. Older versions compile a bit bigger. If its still too large, pls share your computer OS kind and version and your version of Arduino IDE. Thanks and good luck. :) 1.6.5 works for us at 98% space consumed on Win and Mac.
